### PR TITLE
feature: support auto-hide comments when page navigated

### PR DESCRIPTION
**Pull request by 1natsu172**
Issue: #19 

I implemented the feature discussed in the issue.
#21 was submitting from the fork repository, so I resubmitted this PR.

Please review when have time. 🙏

### CODE REVIEW

**Review by dideler — COMMENTED** [review]
Thanks! Code looks good. I'll test it in the browser when I get home.

**Review by dideler — APPROVED** [review]
Tested and works great! 🚀

**Comment by 1natsu172** [comment]
@dideler Thanks for approval.

This is a confirmation for a moment. I think this new feature is not backward compatible (UI doesn't change but UX changes). I'm aware that it is v4.0.0.
If there is no problem merge and release work. Maybe around tomorrow.

**Comment by dideler** [comment]
Hey @1natsu172, I was away for another holiday (this time in Wales) - thanks for your patience.

Would you like to release this feature? Since you built it, you can have the pleasure of shipping it.

**Comment by 1natsu172** [comment]
Welcome back @dideler .

Yes, I'll release this feature. Maybe I can take time tomorrow or the day after tomorrow. (Since I don't have time today, I only reply).

**Comment by 1natsu172** [comment]
@dideler, Now I released it as v4.0.0! 🚀 

I'm very grateful for the discussion at issue #19 and the your user's opinion survey!

**Pull request merged**
