### PR TITLE
:bug: Fix problem: Anti-aliasing isn't applied to "SHOW COMMENTS" button.

### PR DESCRIPTION
**Pull request by 1natsu172**
Issue: #25 

Add style the `-webkit-font-smoothing: antialiased;` . In this PR, font-weight is the same as "SHOW MORE" button. 👀

### CODE REVIEW

**Comment by dideler** [comment]
Looks good 👍

**Review by dideler — APPROVED** [review]

**Comment by 1natsu172** [comment]
Thanks for your reviewed & approved 🙌 
The other day you created a group publisher account. So this time I'll try deploying!

**Comment by 1natsu172** [comment]
Question about versioning. I think that this time is a minor update. Because only the bug fix.
I'm trying to v2.5.1 (current: v2.5.0), so isn't it different from @dideler perception?

**Comment by dideler** [comment]
@1natsu172 that's right, I would do a minor bump for this.

I would personally do two minor bumps (v2.5.1 for #29 and v2.5.2 for #30) to keep version updates granular and focused on a single API, feature, or patch change.

In this case because both PRs are merged, I would suggest creating two tags, but only one commit at the HEAD for the version change to v2.5.2. (Only one commit for the version bump because we don't want to rewrite master history to insert a version update in between the two merge commits.)

**Comment by dideler** [comment]
I've added [a section on releasing to the contributing guide](https://github.com/dideler/toggle-youtube-comments/blob/master/CONTRIBUTING.md#release).

**Comment by dideler** [comment]
@1natsu172 I rewrote https://github.com/dideler/toggle-youtube-comments/pull/30#issuecomment-362829782 because I found my original comment difficult to read - hope it's clearer now.

Also added a bit more info to the contributing guide and created #32 so we have a shared collection of images used historically on the Chrome Web Store. Since this visual change is minor, I personally don't think it'll be worth the effort to take and upload new screenshots, but it's up to you.

**Comment by 1natsu172** [comment]
Thanks for the detailed reply and documentation preparation!

> (Only one commit for the version bump because we don't want to rewrite master history to insert a version update in between the two merge commits.)

I was planning to insert a version between two commits using `git rebase -i`.
But you seem to don't want it, I'll correspond with two tags and one `manifest.json` update(to v2.5.2) this time. From next time I try to separate merge & update one by one. 🙇

**Comment by 1natsu172** [comment]
Bump version to v2.5.2 completed.
I already deployed at chrome web store. So, the extension will be updated with a little time.

**Comment by dideler** [comment]
Congratulations for releasing and publishing the extension!

**Pull request merged**
