### PR TITLE
Add important to margin-left to always apply

### PR DESCRIPTION
**Pull request by katbow**
Fix for #2

### CODE REVIEW

**Comment by dideler** [comment]
Hi @katbow, is this still in progress?

**Comment by katbow** [comment]
@dideler yes! I need to devote some time into looking at events fired when a new video is played. The problem is the show comments button isn't re-rendered when switching from a video with show more to one without (and vice versa).

**Comment by 1natsu172** [comment]
@katbow, Fix this PR & Issue #2 by PR #29 📁 
Please check it. And thanks for submitting this first PR 🙌

**Comment by katbow** [comment]
looks great @1natsu172 ! Thanks for fixing up. Great simple solution 🙂

**Pull request closed without merging**
